# Generated by Django 2.1.1 on 2018-09-20 19:30

import clients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20180920_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='iban',
            field=models.CharField(max_length=34, validators=[clients.validators.validate_iban]),
        ),
    ]
